spring:
  application:
    name: discovery-server

server:
  port: ${PORT:8080}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://tc2-microservice-discovery-server.onrender.com/eureka/
  instance:
    hostname: tc2-microservice-discovery-server.onrender.com
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    prefer-ip-address: false
    status-page-url: https://tc2-microservice-discovery-server.onrender.com/actuator/info
    health-check-url: https://tc2-microservice-discovery-server.onrender.com/actuator/health