spring:
#  profiles:
#    active: local
  application:
    name: discovery-server

server:
  port: ${PORT:8080}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${RENDER_EXTERNAL_URL}/eureka/
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    prefer-ip-address: false
    status-page-url: ${RENDER_EXTERNAL_URL}/actuator/info
    health-check-url: ${RENDER_EXTERNAL_URL}/actuator/health